import React, { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/use-auth';
import { useToast } from '@/hooks/use-toast';
import { debugLog } from '@/lib/debug';
import { UserProfileContext, type UserProfile } from '@/hooks/use-user-profile';

export const UserProfileProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();
  const { toast } = useToast();
  
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [needsUsername, setNeedsUsername] = useState(false);

  // Stabilized profile loading with better state management
  const loadProfile = useCallback(async () => {
    if (!user) {
      setProfile(null);
      setNeedsUsername(false);
      return;
    }

    try {setIsLoading(true);
      
      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', user.id)
        .maybeSingle();

      if (error) {
        console.error('Profile loading error:', error);
        throw new Error("Operation failed");
      } 
      
      if (!data) {
        // No profile - must create username
        setNeedsUsername(true);
        setProfile(null);
      } else {
        // Profile exists - check if username is valid and doesn't need reset
        const isAutoGeneratedUsername = data.username && data.username.startsWith('user_');
        const hasValidUsernameFormat = data.username && 
                                     data.username.length >= 3 && 
                                     /^[a-zA-Z0-9_]+$/.test(data.username);
        
        // User needs username if: explicitly marked for reset OR has auto-generated username
        const needsReset = data.username_reset_required === true || isAutoGeneratedUsername;
        
        setProfile(data);
        setNeedsUsername(needsReset);
        
        debugLog('Profile loaded:', {
          username: data.username,
          isAutoGenerated: isAutoGeneratedUsername,
          resetRequired: data.username_reset_required,
          needsReset
        });
        
        // Only update presence for complete profiles with valid usernames
        if (!needsReset && hasValidUsernameFormat) {
          await updatePresence(true);
        }
      }
    } catch (error) {
      console.error('Error loading profile:', error);
      toast({
        title: "Profile Error",
        description: "Failed to load profile. Please refresh the page.",
        variant: "destructive",
      });
      // Set safe defaults on error
      setProfile(null);
      setNeedsUsername(false);
    } finally {
      setIsLoading(false);
    }
  }, [user, updatePresence, toast]);

  // Check if username is available
  const checkUsernameAvailability = async (username: string): Promise<boolean> => {try {
      const { data, error } = await supabase.rpc('is_username_available', {
        username_to_check: username
      });

      if (error) throw new Error("Operation failed");
      return data;
    } catch (error) {
      console.error('Error checking username availability:', error);
      return false;
    }
  };

  // Robust profile creation with immediate state consistency
  const createProfile = async (username: string, displayName?: string): Promise<boolean> => {
    if (!user) return false;

    try {
      setIsLoading(true);

      // Validate and clean username
      const cleanUsername = username.toLowerCase().trim();
      if (!/^[a-zA-Z0-9_]+$/.test(cleanUsername) || cleanUsername.length < 3) {
        toast({
          title: "Invalid Username",
          description: "Username must be 3-20 characters: letters, numbers, underscores only.",
          variant: "destructive",
        });
        return false;
      }

      // Final availability check
      const isAvailable = await checkUsernameAvailability(cleanUsername);
      if (!isAvailable) {
        toast({
          title: "Username Taken",
          description: "This username is already taken. Please choose another.",
          variant: "destructive",
        });
        return false;
      }

      // Create/update profile with proper error handling
      const {data, error} = await supabase
        .from('profiles')
        .upsert({
          id: user.id,
          username: cleanUsername,
          display_name: displayName?.trim() ?? null,
          is_online: true,
          username_reset_required: false,
          updated_at: new Date().toISOString()
        })
        .select()
        .single();

      if (error) {
        console.error('Profile creation error:', error);
        throw new Error("Operation failed");
      }

      debugLog('Profile created successfully:', {
        username: cleanUsername,
        display_name: displayName,
        user_id: user.id
      });

      // Immediately update state to prevent modal flashing
      setProfile(data);
      setNeedsUsername(false);

      // Background presence update (non-blocking)
      updatePresence(true).catch(console.error);

      toast({
        title: "Welcome!",
        description: `Your profile "${cleanUsername}" has been created.`,
      });

      return true;
    } catch (error) {
      console.error('Profile creation failed:', error);
      toast({
        title: "Creation Failed",
        description: "Could not create profile. Please try again or contact support.",
        variant: "destructive",
      });
      return false;
    } finally {
      setIsLoading(false);
    }
  };

  // Update presence status
  const updatePresence = useCallback(async (isOnline: boolean) => {
    if (!user) return;

    try {
      await supabase.rpc('update_user_presence', {
        user_id: user.id,
        online_status: isOnline
      });
    } catch (error) {
      console.error('Error updating presence:', error);
    }
  }, [user]);

  // Handle going offline
  const goOffline = async () => {
    await updatePresence(false);
  };

  // Set up presence tracking
  useEffect(() => {
    let presenceInterval: NodeJS.Timeout;

    if (user && profile) {
      // Update presence every 30 seconds
      presenceInterval = setInterval(() => {
        updatePresence(true);
      }, 30000);

      // Handle page visibility changes
      const handleVisibilityChange = () => {
        if (document.hidden) {
          updatePresence(false);
        } else {
          updatePresence(true);
        }
      };

      document.addEventListener('visibilitychange', handleVisibilityChange);

      // Handle beforeunload
      const handleBeforeUnload = () => {
        updatePresence(false);
      };

      window.addEventListener('beforeunload', handleBeforeUnload);

      return () => {
        clearInterval(presenceInterval);
        document.removeEventListener('visibilitychange', handleVisibilityChange);
        window.removeEventListener('beforeunload', handleBeforeUnload);
      };
    }
  }, [user, profile, updatePresence]);

  // Load profile when user changes with debounce to prevent race conditions
  useEffect(() => {
    let timeoutId: NodeJS.Timeout;
    
    if (user) {
      // Small delay to ensure auth state is fully settled
      timeoutId = setTimeout(() => {
        loadProfile();
      }, 100);
    } else {
      // Immediately clear profile when user logs out
      setProfile(null);
      setNeedsUsername(false);
    }

    return () => {
      if (timeoutId) clearTimeout(timeoutId);
    };
  }, [user, loadProfile]);

  // Clean up on unmount
  useEffect(() => {
    return () => {
      if (user) {
        updatePresence(false);
      }
    };
  }, [user, updatePresence]);

  const value = {
    profile,
    isLoading,
    needsUsername,
    checkUsernameAvailability,
    createProfile,
    updatePresence,
    goOffline,
    loadProfile,
  };

  return (
    <UserProfileContext.Provider value={value}>
      {children}
    </UserProfileContext.Provider>
  );
};