// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Enhanced environment variable validation
function validateSupabaseConfig() {
  const errors = [];
  
  if (!SUPABASE_URL) {
    errors.push('VITE_SUPABASE_URL is missing');
  } else if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
    errors.push('VITE_SUPABASE_URL format is invalid (should be https://xxx.supabase.co)');
  }
  
  if (!SUPABASE_PUBLISHABLE_KEY) {
    errors.push('VITE_SUPABASE_ANON_KEY is missing');
  } else if (SUPABASE_PUBLISHABLE_KEY.length < 100) {
    errors.push('VITE_SUPABASE_ANON_KEY appears to be invalid (too short)');
  }
  
  if (errors.length > 0) {
    const errorMessage = `Supabase configuration errors:\n${errors.map(e => `- ${e}`).join('\n')}\n\nPlease check your environment variables in .env file.`;
    
    if (typeof window !== 'undefined') {
      console.error('❌ Supabase Configuration Error:', errorMessage);
    }
    
    throw new Error(errorMessage);
  }
  
  // Log successful configuration in development
  if (import.meta.env.DEV) {
    console.warn('✅ Supabase configuration validated successfully');
  }
}

validateSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,  // Ensure localStorage is used
    persistSession: true,     // Enable session persistence 
    autoRefreshToken: true,   // Auto refresh tokens
    detectSessionInUrl: true, // Handle auth redirects
    storageKey: 'supabase.auth.token' // Consistent storage key
  }
});